use schedule;

CREATE TABLE schedule
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT "일정 식별자",
    name VARCHAR(50) COMMENT "작성자 명",
    password VARCHAR(100) COMMENT "비밀번호",
    todo TEXT COMMENT "할일",
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT "작성일",
    update_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT "수정일"
);
